version: '2.1'

services:
  investing.com_scraper:
    image: investing.com_scraper
    build:
      context: .
      args:
        exec: fetch_data.py
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    entrypoint: "bash"
    command: "-c \"pip freeze > requirements.txt && python3 test.py && python3 fetch_data.py && python3 service.py\""