version: '2.1'

services:
  investing.com_scraper:
    image: investing.com_scraper
    build:
      context: .
      args:
        exec: fetch_data.py
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    entrypoint: "sh"
    command: "setup_server.sh"
